# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  kobiton-orb: sonhmle-space/test-first-orb@3.2.14

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - kobiton-orb/upload-app:
          KOBITON_APP_ACCESS: public
          KOBITON_APP_ID: '275643'
          KOBITON_APP_NAME: testandroid
          KOBITON_APP_PATH: ../demo/android-test.apk
      - kobiton-orb/execute-test:
          KOBITON_GIT_REPO_URL: 'https://github.com/sonhmle/azure-devops-sample-java-prod.git'
          KOBITON_APP_ID: kobiton-store:275643
          KOBITON_GIT_REPO_BRANCH: 'master'
          KOBITON_EXECUTOR_URL: 'https://executor-demo.kobiton.com'
          KOBITON_USE_CUSTOM_DEVICE: 'true'
          KOBITON_DEVICE_NAME: 'Galaxy A20s'
          KOBITON_DEVICE_PLATFORM: 'android'
          KOBITON_DEVICE_PLATFORM_VERSION: '10'


