# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  test-first-orb: sonhmle-space/test-first-orb@2.4.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  main:
    jobs:
      - test-first-orb/upload-app:
          KOBITON_APP_PATH: ../demo/another.apk
          KOBITON_APP_NAME: kobiton
          KOBITON_APP_ACCESS: private
      - test-first-orb/upload-app:
          KOBITON_APP_PATH: ../test.apk
          KOBITON_APP_NAME: its


